### ISSUE TITLE
Error in reading cpt data file

### ISSUE THREAD

**Issue by alda30** [hwang051785/pyCPT#1]
Hi,

I am trying to test the code but I get the following:
```
Traceback (most recent call last):
  File "/home/ehsan/pyCPT/01.py", line 8, in <module>
    cpt = pyCPT.CPT('../pyCPT/data/cpt.csv')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/pyCPT/pyCPT.py", line 23, in __init__
    self.element = read_cpt_data(data_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/pyCPT/pyCPT.py", line 184, in read_cpt_data
    element = pyHMRF.Element(data, coord, normalize=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/pyCPT/pyHMRF.py", line 85, in __init__
    self.colors = pseudocolor(self.phys_shp, self.stencil)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/pyCPT/pyHMRF.py", line 785, in pseudocolor
    return np.array([i_w, i_b])
           ^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

```

Can you help?

**Comment by alda30** [comment]
sds
